repository:
  name: rn-diff-purge
  description: "Easier React Native upgrades by clearly exposing changes from a version to another. :rocket: And what better way than to purge, init, then diff? Spoiler: there's no better way. 😎"
  homepage: https://react-native-community.github.io/upgrade-helper
  topics: react-native, upgrade, purge, rn-diff, rn-diff-purge, upgrade-helper

  has_wiki: false
